// redux/favoritesSlice.js
import { createSlice } from '@reduxjs/toolkit';

/**
 * REDUX SLICE: A slice is a collection of Redux reducer logic and actions for a single feature.
 * This slice manages the favorites state for the Quran app.
 */

const initialState = {
  // Array of favorite surahs
  // Each favorite object contains: { surahNumber, surahName, surahNameArabic, revelationPlace, ayahCount }
  favorites: [],
};

const favoritesSlice = createSlice({
  name: 'favorites', // Name of the slice (used in action types)
  initialState,
  
  /**
   * REDUCERS: Functions that specify how the state changes in response to actions.
   * Redux Toolkit uses Immer library internally, so you can write "mutating" logic
   * that actually produces immutable updates.
   */
  reducers: {
    /**
     * ACTION: toggleFavorite
     * Toggles a surah's favorite status (add if not present, remove if present)
     */
    toggleFavorite: (state, action) => {
      const surah = action.payload;
      const index = state.favorites.findIndex(
        (fav) => fav.surahNumber === surah.surahNumber
      );

      if (index >= 0) {
        // Remove if exists
        state.favorites.splice(index, 1);
      } else {
        // Add if doesn't exist
        state.favorites.push(surah);
      }
    },

    /**
     * ACTION: loadFavorites
     * Loads favorites from AsyncStorage (used on app startup)
     */
    loadFavorites: (state, action) => {
      state.favorites = action.payload || [];
    },
  },
});

/**
 * ACTIONS: Export action creators
 * These are automatically generated by createSlice
 */
export const { toggleFavorite, loadFavorites } = favoritesSlice.actions;

/**
 * SELECTORS: Functions to read specific data from the Redux store
 * These help components access the state they need
 */

// Get all favorites
export const selectAllFavorites = (state) => state.favorites.favorites;

// Check if a specific surah is favorited
export const selectIsFavorite = (surahNumber) => (state) => {
  return state.favorites.favorites.some(
    (fav) => fav.surahNumber === surahNumber
  );
};

// Get count of favorites
export const selectFavoritesCount = (state) => state.favorites.favorites.length;

/**
 * REDUCER: Export the reducer to be added to the store
 */
export default favoritesSlice.reducer;
